### ISSUE TITLE
Settings, PostDisplay and Home Page bugs

### ISSUE THREAD

**Issue by flash29** [flash29/this.jobs#135]
- Onclick of this.jobs present in upper left corner, it should redirect to home page.
- Align the search icon with search bar.
- Liking a post is not working - BUG (token might be missing) and CSS change to indicate that user liked this post.
- Clicking on settings should go to UserProfile by default.
- Display error message when applying to a job outisde of validTill date.

**Comment by vangmayi98** [comment]
1. The first bug mentioned here has been fixed.
