### ISSUE TITLE
FrontEnd - Add Search Bar in Navigation Bar

### ISSUE THREAD

**Issue by flash29** [flash29/this.jobs#2]

**Comment by flash29** [comment]
Search bar looks good but the search icon is not clear.

**Comment by flash29** [comment]
you can use the following links where you can download images of icons and use them rather than using a package:
https://ionic.io/ionicons
https://fonts.google.com/

**Comment by vangmayi98** [comment]
@flash29  modified search-icon and removed dependency-based package implementation and replaced it with ionicon images.

**Comment by flash29** [comment]
ok everything looks good closing this issue. Merge it with the develop branch
