### ISSUE TITLE
PostBox Creation

### ISSUE THREAD

**Issue by vangmayi98** [flash29/this.jobs#25]
1. Create a TextBox for PostBox - which allows users to post content 
2. Create Post Options - Photos, Pdfs - with icons representing each of these options  - on the post box
3. Add publish button to the post box - which allows user to share content that he/she wants to post or share to the feed.

Note : Merged the issues #6 #7 and #8 into one issue.

**Comment by flash29** [comment]
Also allow the user to allow a tag option for everypost and the user should not be able to post until a tag is selected

**Comment by VishnuJammula** [comment]
@flash29 @vangmayi98 for this sprint we are supporting only images as part of post creation. Convert image to base64 format and send it along with other fields to create api

**Comment by vangmayi98** [comment]
@flash Please check the PostBox creation so far. If it looks good, we can start working on the routes and values.

**Comment by vangmayi98** [comment]
@flash29  Please check the PostBox creation so far. If it looks good, we can start working on the routes and values.

**Comment by vangmayi98** [comment]
@flash29 completed PoxtBox creation for sprint 1. Please review and we can close this issue after.

**Comment by vangmayi98** [comment]
PostBox created and merged. Closing this issue.
