### ISSUE TITLE
Invalid sql type, during automigrate

### ISSUE THREAD

**Issue by SnehaParuchuri** [flash29/this.jobs#28]
I think the comments array in userposts model is having an issue.

**Comment by VishnuJammula** [comment]
@SnehaParuchuri  why are Likes and Attachments field list of strings?

**Comment by SnehaParuchuri** [comment]
> @SnehaParuchuri why are Likes and Attachments field list of strings?

we need to know the users who have liked the posts to enable the CSS for like button, and attachments can be single object as of now

**Comment by VishnuJammula** [comment]
@SnehaParuchuri Changes related to bug fix can be found at [here](https://github.com/flash29/this.jobs/commit/97fcc289255fd5a0b0a5ac881f6e50c5cff704c3#diff-10e08a419e850eba1ebba18fdd28eb7ec1b7e8baa9bcc3b973e2b8891ec726be). As discussed, supporting slice of strings is not part of this sprint.
