### ISSUE TITLE
FrontEnd - Add Icons and routes in the navigation bar

### ISSUE THREAD

**Issue by flash29** [flash29/this.jobs#3]
Add the following icons and redirect them to different routes when clicked on them : 
1. Home (Where The Feed is displayed).
2. Connections (Where you can check your followers).
3. Jobs (To search for jobs)
4. Settings(Where user can see his profile, update it, change password and look at his activity)
5. Logout

**Comment by vangmayi98** [comment]
Can we close this issue? @flash29
