### ISSUE TITLE
Unable to access endpoints due to CORS

### ISSUE THREAD

**Issue by flash29** [flash29/this.jobs#33]
CORS is not enabled in the backed.
So unable to access the endpoints.
please look into it ASAP.

**Comment by VishnuJammula** [comment]
@flash29 
```
func Cors() gin.HandlerFunc {
    return func(c *gin.Context) {
        c.Writer.Header().Add("Access-Control-Allow-Origin", "*")
        c.Next()
    }
}
```
 put this snip in main.go and in main function put router.Use(Cors()). Can you try this locally. Meanwhile @SnehaParuchuri will fix this issue

**Comment by SnehaParuchuri** [comment]
@flash29 which branch's code should I test this on?

**Comment by flash29** [comment]
Closing this issue as able to access the endpoints from the browser.
Merge this change to the develop branch.
