### ISSUE TITLE
Frontend - Create the TextBox

### ISSUE THREAD

**Issue by vangmayi98** [flash29/this.jobs#6]
Create the textbox for post creation - which allows the users to post content like text, pdf and/or links (hyperlinks).

**Comment by VishnuJammula** [comment]
@vangmayi98 @flash29 How about merging #6 #7 #8 issues into a single bar

**Comment by flash29** [comment]
@vangmayi98 can you merge the issues #6, #7 and #8 into one single issue?

**Comment by vangmayi98** [comment]
Created a new issue #25 merging #6 #7 and #8. Closing this one.
