### ISSUE TITLE
CORS issue for login and register

### ISSUE THREAD

**Issue by vangmayi98** [flash29/this.jobs#61]
![image](https://user-images.githubusercontent.com/35343343/156503192-7e01b1b4-3583-4228-b1ff-36845b31315e.png)

This error occurs for every login and register post or get requests @SnehaParuchuri  @VishnuJammula .  The front-end code for this is available in the RegPage branch.

**Comment by VishnuJammula** [comment]
<img width="394" alt="image" src="https://user-images.githubusercontent.com/24773006/156504650-62b09b96-0b06-43c8-bc2a-8f977584b312.png">
@vangmayi98 look into the URL, it has to be /auth/login. This should be similar to how you are hitting the registration end point

**Comment by VishnuJammula** [comment]
@SnehaParuchuri

**Comment by vangmayi98** [comment]
Issue resolved. Closing it.
